apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    role: data
  name: elasticsearch-svc
  namespace: default
spec:
  clusterIP: 10.96.50.52
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
    role: data
  type: ClusterIP