apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-cluster-config
  namespace: default
data:
  elasticsearch.yaml: |
    cluster.name: es_cluster
    node.master: false
    node.ingest: true
    node.data: true
    http.enabled: true
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 1
    discovery.zen.ping.unicast.hosts: elasticsearch-discovery.default.svc.master.cn
  # elastic_data.yaml: |
  #   cluster.name: es_cluster
  #   node.master: false
  #   node.ingest: true
  #   node.data: true
  #   http.enabled: true
  #   network.host: 0.0.0.0
  #   #ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  #   discovery.zen.ping.unicast.hosts: elasticsearch-discovery.default.svc.master.cn
