apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data1
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  rbd:
    monitors:
    - 192.168.56.50:6789
    pool: rbd
    image: elastic-data1
    user: admin
    secretRef:
      name: ceph-secret
    fsType: xfs
    readOnly: false