apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data-n1
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  rbd:
    monitors:
    - 192.168.56.50:6789
    pool: elastic
    image: d1
    user: admin
    secretRef:
      name: ceph-secret
    fsType: xfs
    readOnly: false